// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"JP_battle_hp","status":true,"description":"V1.0 战斗场景显示战斗双方的血条V1.0.1 MZ版本","parameters":{"----敌人血条设置----":"","enemy_hp":"true","enemy_hp_x":"0","enemy_hp_y":"0","----队友血条设置----":"","player_hp":"true","player_hp_x":"0","player_hp_y":"0"}},
{"name":"AltSaveScreen","status":true,"description":"Alternative save/load screen layout.","parameters":{}}
];
